### ISSUE TITLE
How can I get 'retrieval_results/vqav2/validation_sim_32.npy'?

### ISSUE THREAD

**Issue by haozhezju** [GaryJiajia/OFv2_ICL_VQA#1]
When I run open_flamingo/scripts/run_vqav2.sh, I meet FileNotFoundError: [Errno 2] No such file or directory: 'retrieval_results/vqav2/validation_sim_32.npy'. How can I get 'retrieval_results/vqav2/validation_sim_32.npy'?

**Comment by GaryJiajia** [comment]
You have to run the **retrieval/img2img_clip_style.py** to get the "validation_VQAv2.npy" file
you can train the file name here:
https://github.com/GaryJiajia/OFv2_ICL_VQA/blob/caf62954f6ffce8599131d32f2a982a43681bd1c/retrieval/img2img_clip_style.py#L497
When a retrieval method is needed, change the corresponding preprocess_signals False to True here:
https://github.com/GaryJiajia/OFv2_ICL_VQA/blob/caf62954f6ffce8599131d32f2a982a43681bd1c/retrieval/img2img_clip_style.py#L483-L493

And remember to change the path in **eval/eval_datasets.py** to the generated "validation_VQAv2.npy" file path
https://github.com/GaryJiajia/OFv2_ICL_VQA/blob/caf62954f6ffce8599131d32f2a982a43681bd1c/open_flamingo/eval/eval_datasets.py#L24-L25

**Comment by haozhezju** [comment]
Thank you!
