### ISSUE TITLE
How to get the subdata.json?

### ISSUE THREAD

**Issue by haozhezju** [GaryJiajia/OFv2_ICL_VQA#2]
What is the subdata in "v2_mscoco_val2014_question_subdata.json" and "v2_mscoco_val2014_annotations_subdata.json"? I find "v2_OpenEnded_mscoco_val2014_questions.json" and "v2_mscoco_val2014_annotations.json" but I do not know how to get the subdata.json.

**Comment by aliwister** [comment]
Are the reported experiments performed on the entire validation set or the subdata? If subdata, can you provide the size and the seed used?

**Comment by GaryJiajia** [comment]
> @GaryJiajia Are the reported experiments performed on the entire validation set or the subdata? If subdata, can you provide the size and the seed used?

Our experiments were conducted on a subset of the validation set with 10,000 samples. We have tested on the full validation set, and the results are similar to the subset. Thus, we used the subset to reduce inference time, and the choice of seed has minimal impact on results.
